"""
Auth Infrastructure Generator
================================
Generates React auth infrastructure:
- AuthProvider component with JWT handling
- useAuth() hook
- Token refresh logic
- Permission context

These files are generated ONCE and are meant to be customized.
(Unlike types/services/hooks which are re-generated on every sync.)
"""
from __future__ import annotations


def generate_auth_provider() -> str:
    """Generate AuthProvider.tsx — the main auth context."""
    return '''/**
 * FastForge Auth Provider
 *
 * Generated by FastForge CLI — safe to customize.
 * This file is generated once and will NOT be overwritten.
 */
import React, { createContext, useContext, useState, useEffect, useCallback, useMemo } from "react";
import axios from "axios";
import { configureApiClient } from "../api/apiClient";

// ─── Types ──────────────────────────────────────────────────────────────────

export interface AuthUser {
  id: string | number;
  email: string;
  username?: string;
  roles: string[];
  permissions: string[];
  [key: string]: unknown;
}

export interface AuthTokens {
  accessToken: string;
  refreshToken?: string;
}

export interface AuthState {
  user: AuthUser | null;
  isAuthenticated: boolean;
  isLoading: boolean;
  permissions: Set<string>;
}

export interface AuthActions {
  login: (email: string, password: string) => Promise<void>;
  logout: () => void;
  register: (data: RegisterData) => Promise<void>;
  refreshToken: () => Promise<string | null>;
  hasPermission: (permission: string) => boolean;
  hasAnyPermission: (...permissions: string[]) => boolean;
  hasAllPermissions: (...permissions: string[]) => boolean;
  hasRole: (role: string) => boolean;
}

export interface RegisterData {
  email: string;
  password: string;
  username?: string;
  [key: string]: unknown;
}

type AuthContextType = AuthState & AuthActions;

// ─── Context ────────────────────────────────────────────────────────────────

const AuthContext = createContext<AuthContextType | null>(null);

// ─── Storage Keys ───────────────────────────────────────────────────────────

const STORAGE_KEYS = {
  ACCESS_TOKEN: "fastforge_access_token",
  REFRESH_TOKEN: "fastforge_refresh_token",
  USER: "fastforge_user",
} as const;

// ─── Provider Props ─────────────────────────────────────────────────────────

export interface AuthProviderProps {
  children: React.ReactNode;
  /** Base URL for auth endpoints (default: from API client config) */
  authBaseUrl?: string;
  /** Custom login endpoint (default: /auth/login) */
  loginEndpoint?: string;
  /** Custom register endpoint (default: /auth/register) */
  registerEndpoint?: string;
  /** Custom refresh endpoint (default: /auth/refresh) */
  refreshEndpoint?: string;
  /** Custom user profile endpoint (default: /auth/me) */
  profileEndpoint?: string;
  /** Called after successful login */
  onLogin?: (user: AuthUser) => void;
  /** Called after logout */
  onLogout?: () => void;
  /** Called on auth error (401) */
  onAuthError?: () => void;
}

// ─── Provider ───────────────────────────────────────────────────────────────

export function AuthProvider({
  children,
  authBaseUrl,
  loginEndpoint = "/auth/login",
  registerEndpoint = "/auth/register",
  refreshEndpoint = "/auth/refresh",
  profileEndpoint = "/auth/me",
  onLogin,
  onLogout,
  onAuthError,
}: AuthProviderProps) {
  const [user, setUser] = useState<AuthUser | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [permissions, setPermissions] = useState<Set<string>>(new Set());

  // ── Initialize from stored tokens ──────────────────────────────────────
  useEffect(() => {
    const initAuth = async () => {
      const token = localStorage.getItem(STORAGE_KEYS.ACCESS_TOKEN);
      const storedUser = localStorage.getItem(STORAGE_KEYS.USER);

      if (token && storedUser) {
        try {
          const parsed = JSON.parse(storedUser) as AuthUser;
          setUser(parsed);
          setPermissions(new Set(parsed.permissions || []));
        } catch {
          // Stored data corrupted, try to refresh
          localStorage.removeItem(STORAGE_KEYS.USER);
        }
      }
      setIsLoading(false);
    };

    initAuth();
  }, []);

  // ── Configure API client with token refresh ────────────────────────────
  useEffect(() => {
    configureApiClient({
      baseURL: authBaseUrl,
      onTokenRefresh: async () => {
        return refreshTokenFn();
      },
      onAuthError: () => {
        handleLogout();
        onAuthError?.();
      },
    });
  }, [authBaseUrl]);

  // ── Refresh Token ──────────────────────────────────────────────────────
  const refreshTokenFn = useCallback(async (): Promise<string | null> => {
    const refreshToken = localStorage.getItem(STORAGE_KEYS.REFRESH_TOKEN);
    if (!refreshToken) return null;

    try {
      const { data } = await axios.post(refreshEndpoint, {
        refreshToken,
      });
      const tokens = data as AuthTokens;
      localStorage.setItem(STORAGE_KEYS.ACCESS_TOKEN, tokens.accessToken);
      if (tokens.refreshToken) {
        localStorage.setItem(STORAGE_KEYS.REFRESH_TOKEN, tokens.refreshToken);
      }
      return tokens.accessToken;
    } catch {
      handleLogout();
      return null;
    }
  }, [refreshEndpoint]);

  // ── Login ──────────────────────────────────────────────────────────────
  const login = useCallback(async (email: string, password: string) => {
    const { data } = await axios.post(loginEndpoint, { email, password });
    const { accessToken, refreshToken: rt, user: userData } = data;

    localStorage.setItem(STORAGE_KEYS.ACCESS_TOKEN, accessToken);
    if (rt) localStorage.setItem(STORAGE_KEYS.REFRESH_TOKEN, rt);
    localStorage.setItem(STORAGE_KEYS.USER, JSON.stringify(userData));

    setUser(userData);
    setPermissions(new Set(userData.permissions || []));
    onLogin?.(userData);
  }, [loginEndpoint, onLogin]);

  // ── Register ───────────────────────────────────────────────────────────
  const register = useCallback(async (registerData: RegisterData) => {
    const { data } = await axios.post(registerEndpoint, registerData);
    const { accessToken, refreshToken: rt, user: userData } = data;

    localStorage.setItem(STORAGE_KEYS.ACCESS_TOKEN, accessToken);
    if (rt) localStorage.setItem(STORAGE_KEYS.REFRESH_TOKEN, rt);
    localStorage.setItem(STORAGE_KEYS.USER, JSON.stringify(userData));

    setUser(userData);
    setPermissions(new Set(userData.permissions || []));
    onLogin?.(userData);
  }, [registerEndpoint, onLogin]);

  // ── Logout ─────────────────────────────────────────────────────────────
  const handleLogout = useCallback(() => {
    localStorage.removeItem(STORAGE_KEYS.ACCESS_TOKEN);
    localStorage.removeItem(STORAGE_KEYS.REFRESH_TOKEN);
    localStorage.removeItem(STORAGE_KEYS.USER);
    setUser(null);
    setPermissions(new Set());
    onLogout?.();
  }, [onLogout]);

  // ── Permission Checks ─────────────────────────────────────────────────
  const hasPermission = useCallback(
    (permission: string) => permissions.has(permission),
    [permissions]
  );

  const hasAnyPermission = useCallback(
    (...perms: string[]) => perms.some((p) => permissions.has(p)),
    [permissions]
  );

  const hasAllPermissions = useCallback(
    (...perms: string[]) => perms.every((p) => permissions.has(p)),
    [permissions]
  );

  const hasRole = useCallback(
    (role: string) => user?.roles?.includes(role) ?? false,
    [user]
  );

  // ── Context Value ──────────────────────────────────────────────────────
  const value = useMemo<AuthContextType>(
    () => ({
      user,
      isAuthenticated: !!user,
      isLoading,
      permissions,
      login,
      logout: handleLogout,
      register,
      refreshToken: refreshTokenFn,
      hasPermission,
      hasAnyPermission,
      hasAllPermissions,
      hasRole,
    }),
    [user, isLoading, permissions, login, handleLogout, register,
     refreshTokenFn, hasPermission, hasAnyPermission, hasAllPermissions, hasRole]
  );

  return (
    <AuthContext.Provider value={value}>
      {children}
    </AuthContext.Provider>
  );
}

// ─── Hook ───────────────────────────────────────────────────────────────────

export function useAuth(): AuthContextType {
  const ctx = useContext(AuthContext);
  if (!ctx) {
    throw new Error("useAuth must be used within an <AuthProvider>");
  }
  return ctx;
}
'''


def generate_permission_components() -> str:
    """Generate permission guard components."""
    return '''/**
 * FastForge Permission Guards
 *
 * Generated by FastForge CLI — safe to customize.
 * permission checking for React.
 */
import React from "react";
import { useAuth } from "./AuthProvider";

// ─── RequirePermission Component ────────────────────────────────────────────

interface RequirePermissionProps {
  /** Single permission or array of permissions to check */
  permission: string | string[];
  /** If true, ALL permissions must be present. Default: false (any) */
  requireAll?: boolean;
  /** What to render when permission is denied */
  fallback?: React.ReactNode;
  children: React.ReactNode;
}

/**
 * permission guard component.
 *
 * @example
 * <RequirePermission permission="Products.Create">
 *   <CreateProductButton />
 * </RequirePermission>
 *
 * @example
 * <RequirePermission permission={["Products.Edit", "Products.Delete"]} requireAll>
 *   <AdminPanel />
 * </RequirePermission>
 */
export function RequirePermission({
  permission,
  requireAll = false,
  fallback = null,
  children,
}: RequirePermissionProps) {
  const { hasPermission, hasAnyPermission, hasAllPermissions } = useAuth();

  const perms = Array.isArray(permission) ? permission : [permission];
  const allowed = requireAll
    ? hasAllPermissions(...perms)
    : hasAnyPermission(...perms);

  if (!allowed) return <>{fallback}</>;
  return <>{children}</>;
}

// ─── RequireRole Component ──────────────────────────────────────────────────

interface RequireRoleProps {
  role: string | string[];
  requireAll?: boolean;
  fallback?: React.ReactNode;
  children: React.ReactNode;
}

export function RequireRole({
  role,
  requireAll = false,
  fallback = null,
  children,
}: RequireRoleProps) {
  const { hasRole } = useAuth();
  const roles = Array.isArray(role) ? role : [role];
  const allowed = requireAll
    ? roles.every(hasRole)
    : roles.some(hasRole);

  if (!allowed) return <>{fallback}</>;
  return <>{children}</>;
}

// ─── RequireAuth Component ──────────────────────────────────────────────────

interface RequireAuthProps {
  fallback?: React.ReactNode;
  children: React.ReactNode;
}

export function RequireAuth({ fallback = null, children }: RequireAuthProps) {
  const { isAuthenticated, isLoading } = useAuth();
  if (isLoading) return null;
  if (!isAuthenticated) return <>{fallback}</>;
  return <>{children}</>;
}

// ─── usePermission Hook ─────────────────────────────────────────────────────

/**
 * permission check hook.
 *
 * @example
 * const canCreate = usePermission("Products.Create");
 * const canManage = usePermission(["Products.Edit", "Products.Delete"]);
 */
export function usePermission(permission: string | string[], requireAll = false): boolean {
  const { hasPermission, hasAnyPermission, hasAllPermissions } = useAuth();
  const perms = Array.isArray(permission) ? permission : [permission];
  return requireAll ? hasAllPermissions(...perms) : hasAnyPermission(...perms);
}
'''
