"""
TanStack Query Hooks Generator
================================
Generates React Query hooks for every API endpoint.

GET endpoints → useQuery hooks (with caching, refetch)
POST/PUT/DELETE/PATCH → useMutation hooks (with cache invalidation)

Output: src/api/hooks/{tagName}Hooks.ts
"""
from __future__ import annotations
import re
from .openapi_parser import ParsedSpec, TagGroup, EndpointInfo


def generate_hooks(spec: ParsedSpec) -> dict[str, str]:
    """Generate hook files. Returns dict of {filename: content}."""
    files = {}

    for group in spec.tag_groups:
        filename = _tag_to_hooks_filename(group.tag)
        content = _generate_hooks_file(group, spec)
        files[filename] = content

    # Also generate an index that re-exports everything
    files["index.ts"] = _generate_hooks_index(spec)

    return files


def _generate_hooks_file(group: TagGroup, spec: ParsedSpec) -> str:
    """Generate hooks for one tag group."""
    tag_pascal = _to_pascal(group.tag)
    tag_camel = _to_camel(group.tag)

    # Separate queries vs mutations
    queries = [ep for ep in group.endpoints if not ep.is_mutation]
    mutations = [ep for ep in group.endpoints if ep.is_mutation]

    # Collect imports
    tanstack_imports = set()
    if queries:
        tanstack_imports.update(["useQuery", "UseQueryOptions"])
    if mutations:
        tanstack_imports.update(["useMutation", "useQueryClient", "UseMutationOptions"])

    service_imports = set()
    type_imports = set()
    for ep in group.endpoints:
        service_imports.add(ep.operation_id)
        if ep.response_type:
            _extract_type_names(ep.response_type, type_imports)
        if ep.request_body_type:
            _extract_type_names(ep.request_body_type, type_imports)

    lines = [
        "/**",
        f" * {tag_pascal} React Query Hooks",
        " *",
        " * AUTO-GENERATED by FastForge CLI — do not edit manually.",
        " */",
        f'import {{ {", ".join(sorted(tanstack_imports))} }} from "@tanstack/react-query";',
        f'import {{ {", ".join(sorted(service_imports))} }} from "../services/{tag_camel}Service";',
    ]

    if type_imports:
        lines.append(f'import type {{ {", ".join(sorted(type_imports))} }} from "../types";')

    lines.append("")

    # ── Query Key Factory ─────────────────────────────────────────────────
    lines.append(f"// ─── Query Keys ──────────────────────────────────────────────────────────\n")
    lines.append(f"export const {tag_camel}Keys = {{")
    lines.append(f'  all: ["{tag_camel}"] as const,')

    for ep in queries:
        key_name = _op_to_key_name(ep.operation_id)
        path_params = [p for p in ep.parameters if p.location == "path"]
        query_params = [p for p in ep.parameters if p.location == "query"]

        if path_params:
            param_names = ", ".join(f"{p.name}: {p.ts_type}" for p in path_params)
            param_values = ", ".join(p.name for p in path_params)
            lines.append(f'  {key_name}: ({{{param_names}}}) => ["{tag_camel}", "{key_name}", {param_values}] as const,')
        elif query_params:
            lines.append(f'  {key_name}: (params?: Record<string, unknown>) => ["{tag_camel}", "{key_name}", params] as const,')
        else:
            lines.append(f'  {key_name}: ["{tag_camel}", "{key_name}"] as const,')

    lines.append("};")
    lines.append("")

    # ── Query Hooks ───────────────────────────────────────────────────────
    if queries:
        lines.append("// ─── Query Hooks ─────────────────────────────────────────────────────────\n")
        for ep in queries:
            lines.append(_generate_query_hook(ep, tag_camel))
            lines.append("")

    # ── Mutation Hooks ────────────────────────────────────────────────────
    if mutations:
        lines.append("// ─── Mutation Hooks ──────────────────────────────────────────────────────\n")
        for ep in mutations:
            lines.append(_generate_mutation_hook(ep, tag_camel))
            lines.append("")

    return "\n".join(lines)


def _generate_query_hook(ep: EndpointInfo, tag_camel: str) -> str:
    """Generate a useQuery hook for a GET endpoint."""
    hook_name = f"use{_to_pascal(ep.operation_id)}"
    return_type = ep.response_type or "unknown"
    key_name = _op_to_key_name(ep.operation_id)

    path_params = [p for p in ep.parameters if p.location == "path"]
    query_params = [p for p in ep.parameters if p.location == "query"]

    lines = []

    if ep.summary:
        lines.append(f"/** {ep.summary} */")

    # Build hook params
    hook_params = []
    fn_call_args = []

    if path_params:
        for p in path_params:
            hook_params.append(f"{p.name}: {p.ts_type}")
            fn_call_args.append(p.name)

    if query_params:
        opts = []
        for p in query_params:
            opt = "" if p.required else "?"
            opts.append(f"    {p.name}{opt}: {p.ts_type};")
        hook_params.append("params?: {\n" + "\n".join(opts) + "\n  }")
        fn_call_args.append("params")

    hook_params.append(f"options?: Partial<UseQueryOptions<{return_type}>>")

    # Build query key
    if path_params:
        param_obj = ", ".join(f"{p.name}" for p in path_params)
        query_key = f"{tag_camel}Keys.{key_name}({{ {param_obj} }})"
    elif query_params:
        query_key = f"{tag_camel}Keys.{key_name}(params)"
    else:
        query_key = f"{tag_camel}Keys.{key_name}"

    # Build service call
    call_args = ", ".join(fn_call_args)

    lines.append(f"export function {hook_name}({', '.join(hook_params)}) {{")
    lines.append(f"  return useQuery({{")
    lines.append(f"    queryKey: {query_key},")
    lines.append(f"    queryFn: () => {ep.operation_id}({call_args}),")

    # Add enabled flag for hooks with required path params
    if path_params:
        conditions = " && ".join(f"{p.name} !== undefined" for p in path_params)
        lines.append(f"    enabled: {conditions},")

    lines.append(f"    ...options,")
    lines.append(f"  }});")
    lines.append("}")

    return "\n".join(lines)


def _generate_mutation_hook(ep: EndpointInfo, tag_camel: str) -> str:
    """Generate a useMutation hook for POST/PUT/DELETE/PATCH."""
    hook_name = f"use{_to_pascal(ep.operation_id)}"
    return_type = ep.response_type or "void"

    lines = []

    if ep.summary:
        lines.append(f"/** {ep.summary} */")

    # Determine mutation variable type
    path_params = [p for p in ep.parameters if p.location == "path"]
    mutation_var_parts = []

    if path_params:
        for p in path_params:
            mutation_var_parts.append(f"{p.name}: {p.ts_type}")

    if ep.request_body_type:
        mutation_var_parts.append(f"data: {ep.request_body_type}")

    if mutation_var_parts:
        mutation_var_type = "{ " + "; ".join(mutation_var_parts) + " }"
    else:
        mutation_var_type = "void"

    lines.append(f"export function {hook_name}(")
    lines.append(f"  options?: UseMutationOptions<{return_type}, Error, {mutation_var_type}>")
    lines.append(f") {{")
    lines.append(f"  const queryClient = useQueryClient();")
    lines.append(f"")
    lines.append(f"  return useMutation({{")

    # Build mutationFn
    if mutation_var_type == "void":
        lines.append(f"    mutationFn: () => {ep.operation_id}(),")
    else:
        # Destructure params
        destructure_parts = []
        call_args = []
        if path_params:
            for p in path_params:
                destructure_parts.append(p.name)
                call_args.append(p.name)
        if ep.request_body_type:
            destructure_parts.append("data")
            call_args.append("data")

        destructure = ", ".join(destructure_parts)
        call = ", ".join(call_args)
        lines.append(f"    mutationFn: ({{ {destructure} }}) => {ep.operation_id}({call}),")

    # Auto-invalidate the tag's queries on mutation success
    lines.append(f"    onSuccess: (...args) => {{")
    lines.append(f'      queryClient.invalidateQueries({{ queryKey: {tag_camel}Keys.all }});')
    lines.append(f"      options?.onSuccess?.(...args);")
    lines.append(f"    }},")
    lines.append(f"    ...options,")
    lines.append(f"  }});")
    lines.append("}")

    return "\n".join(lines)


def _generate_hooks_index(spec: ParsedSpec) -> str:
    """Generate index.ts that re-exports all hooks."""
    lines = [
        "/**",
        " * FastForge API Hooks — re-exports all generated hooks.",
        " *",
        " * AUTO-GENERATED by FastForge CLI — do not edit manually.",
        " */",
    ]
    for group in spec.tag_groups:
        filename = _tag_to_hooks_filename(group.tag).replace(".ts", "")
        lines.append(f'export * from "./{filename}";')

    return "\n".join(lines)


# ─── Helpers ─────────────────────────────────────────────────────────────────

def _op_to_key_name(operation_id: str) -> str:
    """Convert operation ID to a query key name."""
    # listProducts → list, getProduct → detail, etc.
    return operation_id


def _extract_type_names(type_str: str, refs: set[str]):
    for match in re.finditer(r'\b([A-Z][a-zA-Z0-9]+)\b', type_str):
        name = match.group(1)
        if name not in ("Promise", "Record", "Partial", "Required", "Array",
                        "UseQueryOptions", "UseMutationOptions", "Error"):
            refs.add(name)


def _tag_to_hooks_filename(tag: str) -> str:
    return f"use{_to_pascal(tag)}.ts"


def _to_pascal(s: str) -> str:
    return re.sub(r'(?:^|[_\-\s]+)(.)', lambda m: m.group(1).upper(), s)


def _to_camel(s: str) -> str:
    pascal = _to_pascal(s)
    return pascal[0].lower() + pascal[1:] if pascal else ""
