"""
TypeScript Types Generator
============================
Generates TypeScript interfaces and enums from parsed OpenAPI schemas.

Output: src/api/types.ts
"""
from __future__ import annotations
from .openapi_parser import ParsedSpec, SchemaInfo, PropertyInfo


def generate_types(spec: ParsedSpec) -> str:
    """Generate a complete types.ts file from parsed schemas."""
    lines = [
        "/**",
        f" * {spec.title} — API Types",
        f" * Version: {spec.version}",
        " *",
        " * AUTO-GENERATED by FastForge CLI — do not edit manually.",
        f" * Re-generate with: fastforge generate-client",
        " */",
        "",
    ]

    # Sort schemas: enums first, then interfaces
    enums = [s for s in spec.schemas if s.is_enum]
    interfaces = [s for s in spec.schemas if not s.is_enum]

    # Enums
    if enums:
        lines.append("// ─── Enums ────────────────────────────────────────────────────────────────\n")
        for schema in enums:
            lines.append(_generate_enum(schema))
            lines.append("")

    # Interfaces
    if interfaces:
        lines.append("// ─── Interfaces ──────────────────────────────────────────────────────────\n")
        for schema in interfaces:
            lines.append(_generate_interface(schema))
            lines.append("")

    return "\n".join(lines)


def _generate_enum(schema: SchemaInfo) -> str:
    """Generate a TypeScript enum or string union type."""
    lines = []
    if schema.description:
        lines.append(f"/** {schema.description} */")

    # Use string literal union for string enums (more idiomatic TS)
    if all(isinstance(v, str) for v in schema.enum_values):
        values = " | ".join(f'"{v}"' for v in schema.enum_values)
        lines.append(f"export type {schema.name} = {values};")
    else:
        # Use const enum for numeric enums
        lines.append(f"export enum {schema.name} {{")
        for v in schema.enum_values:
            if isinstance(v, str):
                safe_name = v.replace(" ", "_").replace("-", "_").upper()
                lines.append(f'  {safe_name} = "{v}",')
            else:
                lines.append(f"  VALUE_{v} = {v},")
        lines.append("}")

    return "\n".join(lines)


def _generate_interface(schema: SchemaInfo) -> str:
    """Generate a TypeScript interface from a schema."""
    lines = []

    if schema.description:
        lines.append(f"/** {schema.description} */")

    extends = f" extends {schema.extends}" if schema.extends else ""
    lines.append(f"export interface {schema.name}{extends} {{")

    for prop in schema.properties:
        # JSDoc comment for the property
        if prop.description:
            lines.append(f"  /** {prop.description} */")

        opt = "" if prop.required else "?"
        ts_type = prop.ts_type

        # Clean up null unions for optional fields
        if not prop.required and " | null" in ts_type:
            ts_type = ts_type.replace(" | null", "")

        lines.append(f"  {_safe_prop_name(prop.name)}{opt}: {ts_type};")

    lines.append("}")
    return "\n".join(lines)


def _safe_prop_name(name: str) -> str:
    """Ensure property name is valid TypeScript."""
    # If name contains special chars, wrap in quotes
    if not name.isidentifier() or name in _TS_RESERVED:
        return f'"{name}"'
    return name


_TS_RESERVED = {
    "break", "case", "catch", "class", "const", "continue", "debugger",
    "default", "delete", "do", "else", "enum", "export", "extends",
    "false", "finally", "for", "function", "if", "import", "in",
    "instanceof", "new", "null", "return", "super", "switch", "this",
    "throw", "true", "try", "typeof", "var", "void", "while", "with",
    "yield", "type", "interface", "implements", "package", "private",
    "protected", "public", "static",
}
