"""
API Service Generator
======================
Generates typed Axios-based service functions from parsed OpenAPI endpoints.

For each tag group, generates a service file:
  src/api/services/productService.ts
  src/api/services/userService.ts

Each service function is fully typed with request params, body, and response.
"""
from __future__ import annotations
import re
from .openapi_parser import ParsedSpec, TagGroup, EndpointInfo, ParameterInfo


def generate_services(spec: ParsedSpec) -> dict[str, str]:
    """
    Generate service files. Returns dict of {filename: content}.
    One file per tag group.
    """
    files = {}

    for group in spec.tag_groups:
        filename = _tag_to_filename(group.tag)
        content = _generate_service_file(group, spec)
        files[filename] = content

    return files


def generate_api_client(spec: ParsedSpec) -> str:
    """Generate the base Axios API client configuration."""
    return f'''/**
 * FastForge API Client
 *
 * AUTO-GENERATED by FastForge CLI — do not edit manually.
 * Customize by editing fastforge.config.ts instead.
 */
import axios, {{ AxiosInstance, AxiosRequestConfig, AxiosError }} from "axios";

// ─── Configuration ──────────────────────────────────────────────────────────

export interface ApiClientConfig {{
  baseURL: string;
  timeout?: number;
  onTokenRefresh?: () => Promise<string | null>;
  onAuthError?: (error: AxiosError) => void;
}}

const DEFAULT_CONFIG: ApiClientConfig = {{
  baseURL: import.meta.env.VITE_API_URL || "{spec.base_url}" || "http://localhost:8000/api/v1",
  timeout: 30000,
}};

// ─── Create Client ──────────────────────────────────────────────────────────

let _config = {{ ...DEFAULT_CONFIG }};
let _client: AxiosInstance | null = null;

export function configureApiClient(config: Partial<ApiClientConfig>) {{
  _config = {{ ...DEFAULT_CONFIG, ...config }};
  _client = null; // Force re-creation
}}

export function getApiClient(): AxiosInstance {{
  if (_client) return _client;

  _client = axios.create({{
    baseURL: _config.baseURL,
    timeout: _config.timeout,
    headers: {{
      "Content-Type": "application/json",
    }},
  }});

  // ── Request Interceptor: Attach JWT ──────────────────────────────────
  _client.interceptors.request.use(
    (config) => {{
      const token = typeof window !== "undefined"
        ? localStorage.getItem("fastforge_access_token")
        : null;
      if (token && config.headers) {{
        config.headers.Authorization = `Bearer ${{token}}`;
      }}
      return config;
    }},
    (error) => Promise.reject(error)
  );

  // ── Response Interceptor: Handle 401 + Token Refresh ────────────────
  _client.interceptors.response.use(
    (response) => response,
    async (error: AxiosError) => {{
      const originalRequest = error.config as AxiosRequestConfig & {{ _retry?: boolean }};

      if (error.response?.status === 401 && !originalRequest._retry) {{
        originalRequest._retry = true;

        if (_config.onTokenRefresh) {{
          try {{
            const newToken = await _config.onTokenRefresh();
            if (newToken) {{
              localStorage.setItem("fastforge_access_token", newToken);
              if (originalRequest.headers) {{
                originalRequest.headers.Authorization = `Bearer ${{newToken}}`;
              }}
              return getApiClient()(originalRequest);
            }}
          }} catch {{
            // Token refresh failed
          }}
        }}

        // Auth failed completely
        if (_config.onAuthError) {{
          _config.onAuthError(error);
        }}
      }}

      return Promise.reject(error);
    }}
  );

  return _client;
}}

// ─── Typed Request Helpers ──────────────────────────────────────────────────

export async function apiGet<T>(url: string, params?: Record<string, unknown>): Promise<T> {{
  const {{ data }} = await getApiClient().get<T>(url, {{ params }});
  return data;
}}

export async function apiPost<T>(url: string, body?: unknown): Promise<T> {{
  const {{ data }} = await getApiClient().post<T>(url, body);
  return data;
}}

export async function apiPut<T>(url: string, body?: unknown): Promise<T> {{
  const {{ data }} = await getApiClient().put<T>(url, body);
  return data;
}}

export async function apiPatch<T>(url: string, body?: unknown): Promise<T> {{
  const {{ data }} = await getApiClient().patch<T>(url, body);
  return data;
}}

export async function apiDelete<T>(url: string): Promise<T> {{
  const {{ data }} = await getApiClient().delete<T>(url);
  return data;
}}
'''


def _generate_service_file(group: TagGroup, spec: ParsedSpec) -> str:
    """Generate a single service file for a tag group."""
    tag_pascal = _to_pascal(group.tag)
    tag_camel = _to_camel(group.tag)

    # Collect all types referenced by this group's endpoints
    referenced_types = set()
    for ep in group.endpoints:
        _collect_type_refs(ep, referenced_types)

    # Build imports
    lines = [
        "/**",
        f" * {tag_pascal} API Service",
        " *",
        " * AUTO-GENERATED by FastForge CLI — do not edit manually.",
        " */",
    ]

    # Import from apiClient
    api_imports = set()
    for ep in group.endpoints:
        if ep.method == "GET":
            api_imports.add("apiGet")
        elif ep.method == "POST":
            api_imports.add("apiPost")
        elif ep.method == "PUT":
            api_imports.add("apiPut")
        elif ep.method == "PATCH":
            api_imports.add("apiPatch")
        elif ep.method == "DELETE":
            api_imports.add("apiDelete")

    lines.append(f'import {{ {", ".join(sorted(api_imports))} }} from "../apiClient";')

    # Import types
    if referenced_types:
        lines.append(f'import type {{ {", ".join(sorted(referenced_types))} }} from "../types";')

    lines.append("")

    # Generate each endpoint function
    for ep in group.endpoints:
        lines.append(_generate_endpoint_function(ep))
        lines.append("")

    return "\n".join(lines)


def _generate_endpoint_function(ep: EndpointInfo) -> str:
    """Generate a single typed service function."""
    lines = []

    # JSDoc
    if ep.summary or ep.description:
        lines.append("/**")
        if ep.summary:
            lines.append(f" * {ep.summary}")
        if ep.description and ep.description != ep.summary:
            lines.append(f" * {ep.description}")
        lines.append(" */")

    # Build function signature
    params = _build_function_params(ep)
    return_type = ep.response_type or "void"
    fn_name = ep.operation_id

    # Path with interpolation
    path = _build_path_template(ep)

    # Query params
    query_params = [p for p in ep.parameters if p.location == "query"]

    if ep.method == "GET":
        if query_params:
            lines.append(f"export async function {fn_name}({params}): Promise<{return_type}> {{")
            query_obj = _build_query_object(query_params)
            lines.append(f"  return apiGet<{return_type}>({path}, {query_obj});")
        else:
            lines.append(f"export async function {fn_name}({params}): Promise<{return_type}> {{")
            lines.append(f"  return apiGet<{return_type}>({path});")

    elif ep.method == "POST":
        body_param = "data" if ep.request_body_type else "undefined"
        lines.append(f"export async function {fn_name}({params}): Promise<{return_type}> {{")
        lines.append(f"  return apiPost<{return_type}>({path}, {body_param});")

    elif ep.method == "PUT":
        body_param = "data" if ep.request_body_type else "undefined"
        lines.append(f"export async function {fn_name}({params}): Promise<{return_type}> {{")
        lines.append(f"  return apiPut<{return_type}>({path}, {body_param});")

    elif ep.method == "PATCH":
        body_param = "data" if ep.request_body_type else "undefined"
        lines.append(f"export async function {fn_name}({params}): Promise<{return_type}> {{")
        lines.append(f"  return apiPatch<{return_type}>({path}, {body_param});")

    elif ep.method == "DELETE":
        lines.append(f"export async function {fn_name}({params}): Promise<{return_type}> {{")
        lines.append(f"  return apiDelete<{return_type}>({path});")

    lines.append("}")
    return "\n".join(lines)


def _build_function_params(ep: EndpointInfo) -> str:
    """Build the function parameter string."""
    params = []

    # Path params first
    for p in ep.parameters:
        if p.location == "path":
            params.append(f"{p.name}: {p.ts_type}")

    # Request body
    if ep.request_body_type:
        opt = "" if ep.request_body_required else "?"
        params.append(f"data{opt}: {ep.request_body_type}")

    # Query params as options object
    query_params = [p for p in ep.parameters if p.location == "query"]
    if query_params:
        opts = []
        for p in query_params:
            opt = "" if p.required else "?"
            opts.append(f"    {p.name}{opt}: {p.ts_type};")
        params.append("params?: {\n" + "\n".join(opts) + "\n  }")

    return ", ".join(params)


def _build_path_template(ep: EndpointInfo) -> str:
    r"""Convert /products/{id} to template literal `/products/${id}`."""
    path = ep.path
    # Replace {param} with ${param}
    path = re.sub(r'\{(\w+)\}', r'${\1}', path)
    if "${" in path:
        return f'`{path}`'
    return f'"{path}"'


def _build_query_object(params: list[ParameterInfo]) -> str:
    """Build query params object for Axios."""
    entries = ", ".join(f"{p.name}: params?.{p.name}" for p in params)
    return f"{{ {entries} }}"


def _collect_type_refs(ep: EndpointInfo, refs: set[str]):
    """Collect all type names referenced by an endpoint."""
    if ep.request_body_type:
        _extract_type_names(ep.request_body_type, refs)
    if ep.response_type:
        _extract_type_names(ep.response_type, refs)


def _extract_type_names(type_str: str, refs: set[str]):
    """Extract concrete type names from a TS type string."""
    # Match PascalCase words that look like type references
    for match in re.finditer(r'\b([A-Z][a-zA-Z0-9]+)\b', type_str):
        name = match.group(1)
        if name not in ("Promise", "Record", "Partial", "Required", "Array"):
            refs.add(name)


def _tag_to_filename(tag: str) -> str:
    """Convert a tag name to a service filename."""
    # "Product" → "productService.ts"
    camel = _to_camel(tag)
    return f"{camel}Service.ts"


def _to_pascal(s: str) -> str:
    return re.sub(r'(?:^|[_\-\s]+)(.)', lambda m: m.group(1).upper(), s)


def _to_camel(s: str) -> str:
    pascal = _to_pascal(s)
    return pascal[0].lower() + pascal[1:] if pascal else ""
