"""
generate-client Command
========================
The core Phase 1 command. Reads your FastAPI's OpenAPI spec and generates
the complete frontend API infrastructure.

Usage:
  fastforge generate-client                          # Uses fastforge.json config
  fastforge generate-client --input http://localhost:8000/openapi.json
  fastforge generate-client --input ./openapi.json --output ./src/api
"""
from __future__ import annotations
import os
import json
import shutil
from pathlib import Path
from datetime import datetime

from .openapi_parser import load_spec, parse_openapi, ParsedSpec
from .gen_types import generate_types
from .gen_services import generate_services, generate_api_client
from .gen_hooks import generate_hooks
from .gen_auth import generate_auth_provider, generate_permission_components


# ─── Configuration ───────────────────────────────────────────────────────────

DEFAULT_OUTPUT_DIR = "src/api"
GENERATED_MARKER = "AUTO-GENERATED by FastForge CLI"

# Files that are generated ONCE and never overwritten
PROTECTED_FILES = {
    "auth/AuthProvider.tsx",
    "auth/PermissionGuards.tsx",
}


def run_generate_client(
    input_source: str,
    output_dir: str = DEFAULT_OUTPUT_DIR,
    skip_auth: bool = False,
    verbose: bool = False,
):
    """
    Main entry point for the generate-client command.
    
    1. Load & parse the OpenAPI spec
    2. Generate TypeScript types
    3. Generate API service functions  
    4. Generate TanStack Query hooks
    5. Generate auth infrastructure (once)
    6. Generate index files
    """
    output = Path(output_dir)

    print(f"\n⚡ FastForge — Generating frontend client\n")
    print(f"  Source: {input_source}")
    print(f"  Output: {output_dir}")
    print()

    # ── Step 1: Load & Parse ─────────────────────────────────────────────
    print("📖 Loading OpenAPI spec...")
    try:
        spec_data = load_spec(input_source)
    except Exception as e:
        print(f"  ❌ Failed to load spec: {e}")
        return False

    spec = parse_openapi(spec_data)
    print(f"  ✅ Parsed: {spec.title} v{spec.version}")
    print(f"  📊 {len(spec.schemas)} schemas, {len(spec.all_endpoints)} endpoints, {len(spec.tag_groups)} tag groups")
    print()

    # ── Step 2: Generate Types ───────────────────────────────────────────
    print("📝 Generating TypeScript types...")
    types_content = generate_types(spec)
    _write_file(output / "types.ts", types_content, overwrite=True)

    # ── Step 3: Generate API Client ──────────────────────────────────────
    print("🔌 Generating API client...")
    client_content = generate_api_client(spec)
    _write_file(output / "apiClient.ts", client_content, overwrite=True)

    # ── Step 4: Generate Services ────────────────────────────────────────
    print("🛠️  Generating service functions...")
    services = generate_services(spec)
    services_dir = output / "services"
    _ensure_dir(services_dir)

    # Generate service index
    service_index_lines = [
        f"// {GENERATED_MARKER}",
    ]
    for filename, content in services.items():
        _write_file(services_dir / filename, content, overwrite=True)
        module = filename.replace(".ts", "")
        service_index_lines.append(f'export * from "./{module}";')
    _write_file(services_dir / "index.ts", "\n".join(service_index_lines), overwrite=True)

    # ── Step 5: Generate Hooks ───────────────────────────────────────────
    print("🪝 Generating TanStack Query hooks...")
    hooks = generate_hooks(spec)
    hooks_dir = output / "hooks"
    _ensure_dir(hooks_dir)

    for filename, content in hooks.items():
        _write_file(hooks_dir / filename, content, overwrite=True)

    # ── Step 6: Generate Auth (once) ─────────────────────────────────────
    if not skip_auth:
        print("🔐 Generating auth infrastructure...")
        auth_dir = output / "auth"
        _ensure_dir(auth_dir)

        auth_provider = generate_auth_provider()
        _write_file(auth_dir / "AuthProvider.tsx", auth_provider, overwrite=False)

        permissions = generate_permission_components()
        _write_file(auth_dir / "PermissionGuards.tsx", permissions, overwrite=False)

        # Auth index
        auth_index = "\n".join([
            f"// {GENERATED_MARKER}",
            'export { AuthProvider, useAuth } from "./AuthProvider";',
            'export type { AuthUser, AuthProviderProps, RegisterData } from "./AuthProvider";',
            'export { RequirePermission, RequireRole, RequireAuth, usePermission } from "./PermissionGuards";',
        ])
        _write_file(auth_dir / "index.ts", auth_index, overwrite=True)

    # ── Step 7: Root Index ───────────────────────────────────────────────
    print("📦 Generating index...")
    root_index = _generate_root_index(spec, skip_auth)
    _write_file(output / "index.ts", root_index, overwrite=True)

    # ── Step 8: Generate Config ──────────────────────────────────────────
    config_file = output / "fastforge.generated.json"
    config = {
        "generatedAt": datetime.now().isoformat(),
        "source": input_source,
        "apiTitle": spec.title,
        "apiVersion": spec.version,
        "schemas": len(spec.schemas),
        "endpoints": len(spec.all_endpoints),
        "tagGroups": [g.tag for g in spec.tag_groups],
    }
    _write_file(config_file, json.dumps(config, indent=2), overwrite=True)

    # ── Summary ──────────────────────────────────────────────────────────
    print()
    print("─" * 60)
    print("✅ Client generated successfully!")
    print("─" * 60)
    print()
    print(f"  📁 {output_dir}/")
    print(f"     ├── types.ts              — {len(spec.schemas)} TypeScript interfaces")
    print(f"     ├── apiClient.ts           — Axios client with JWT interceptors")
    print(f"     ├── services/              — {len(services)} service files")
    for fname in sorted(services.keys()):
        tag_eps = [ep for g in spec.tag_groups for ep in g.endpoints if _tag_to_filename(g.tag) == fname]
        print(f"     │   ├── {fname}")
    print(f"     ├── hooks/                 — TanStack Query hooks")
    for fname in sorted(hooks.keys()):
        print(f"     │   ├── {fname}")
    if not skip_auth:
        print(f"     ├── auth/")
        print(f"     │   ├── AuthProvider.tsx    — JWT auth context + useAuth()")
        print(f"     │   └── PermissionGuards.tsx — <RequirePermission> + usePermission()")
    print(f"     └── index.ts               — Re-exports everything")
    print()
    print("  Usage in your React app:")
    print()
    print('    import { useAuth, useListProducts, productKeys } from "./api";')
    print()

    return True


def _generate_root_index(spec: ParsedSpec, skip_auth: bool) -> str:
    """Generate the main index.ts that re-exports everything."""
    lines = [
        "/**",
        f" * {spec.title} — Generated API Client",
        " *",
        f" * {GENERATED_MARKER}",
        " */",
        "",
        "// Types",
        'export * from "./types";',
        "",
        "// API Client",
        'export { configureApiClient, getApiClient, apiGet, apiPost, apiPut, apiPatch, apiDelete } from "./apiClient";',
        'export type { ApiClientConfig } from "./apiClient";',
        "",
        "// Services",
        'export * from "./services";',
        "",
        "// Hooks",
        'export * from "./hooks";',
    ]

    if not skip_auth:
        lines.extend([
            "",
            "// Auth",
            'export * from "./auth";',
        ])

    return "\n".join(lines)


# ─── File Helpers ────────────────────────────────────────────────────────────

def _ensure_dir(path: Path):
    path.mkdir(parents=True, exist_ok=True)


def _write_file(path: Path, content: str, overwrite: bool = True):
    """Write a file, respecting the overwrite flag for protected files."""
    rel_path = str(path)

    if path.exists() and not overwrite:
        print(f"  ⏭ Skipped (exists): {rel_path}")
        return

    _ensure_dir(path.parent)
    path.write_text(content)
    action = "Updated" if path.exists() else "Created"
    print(f"  ✅ {action}: {rel_path}")


def _tag_to_filename(tag: str) -> str:
    import re
    pascal = re.sub(r'(?:^|[_\-\s]+)(.)', lambda m: m.group(1).upper(), tag)
    camel = pascal[0].lower() + pascal[1:] if pascal else ""
    return f"{camel}Service.ts"
