"""
FastForge CRUD Application Service
======================================
application service base. Generated CRUD services extend this.

Provides:
  - Standard CRUD operations (get, list, create, update, delete)
  - Automatic Pydantic ↔ SQLAlchemy mapping
  - Error handling with proper HTTP exceptions
  - Permission checking hooks

Usage (auto-generated by `fastforge crud`):
    class ProductService(CrudAppService[Product, ProductCreate, ProductUpdate, ProductResponse]):
        def __init__(self, db: Session, user_id=None, tenant_id=None):
            repo = ProductRepository(db, Product, user_id, tenant_id)
            super().__init__(repo, ProductResponse)
"""
from __future__ import annotations
from typing import TypeVar, Generic, Type, Optional, Any
from fastapi import HTTPException, status
from pydantic import BaseModel
from sqlalchemy.orm import Session
import math

from .repository import GenericRepository, PagedResult
from .entities import Base

TEntity = TypeVar("TEntity", bound=Base)
TCreate = TypeVar("TCreate", bound=BaseModel)
TUpdate = TypeVar("TUpdate", bound=BaseModel)
TResponse = TypeVar("TResponse", bound=BaseModel)


class CrudAppService(Generic[TEntity, TCreate, TUpdate, TResponse]):
    """
    Base CRUD application service.
    Handles the standard get/list/create/update/delete workflow.

    Override hooks for custom business logic:
      - before_create(data) → called before insert
      - after_create(entity) → called after insert
      - before_update(entity, data) → called before update
      - after_update(entity) → called after update
      - before_delete(entity) → called before delete
      - map_to_response(entity) → custom entity → response mapping
    """

    def __init__(
        self,
        repository: GenericRepository[TEntity],
        response_model: Type[TResponse],
    ):
        self.repo = repository
        self.response_model = response_model

    # ─── Read Operations ─────────────────────────────────────────────────

    def get(self, id: int) -> TResponse:
        """Get single entity by ID. Raises 404 if not found."""
        entity = self.repo.get_by_id(id)
        if not entity:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"{self.repo.model_class.__name__} with id {id} not found",
            )
        return self.map_to_response(entity)

    def get_list(
        self,
        page: int = 1,
        page_size: int = 20,
        search: Optional[str] = None,
        sort_by: Optional[str] = None,
        sort_order: Optional[str] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> dict:
        """
        Get paginated list. Returns dict matching the ListResponse schema.
        """
        result = self.repo.get_list(
            page=page,
            page_size=page_size,
            search=search,
            sort_by=sort_by,
            sort_order=sort_order,
            filters=filters,
        )
        return {
            "items": [self.map_to_response(item) for item in result.items],
            "total": result.total,
            "page": result.page,
            "page_size": result.page_size,
            "total_pages": result.total_pages,
        }

    # ─── Write Operations ────────────────────────────────────────────────

    def create(self, data: TCreate) -> TResponse:
        """Create a new entity from Pydantic schema."""
        # Hook: before create
        self.before_create(data)

        entity = self.repo.create_from_dict(data.model_dump())

        # Hook: after create
        self.after_create(entity)

        return self.map_to_response(entity)

    def update(self, id: int, data: TUpdate) -> TResponse:
        """Update an existing entity. Raises 404 if not found."""
        entity = self.repo.get_by_id(id)
        if not entity:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"{self.repo.model_class.__name__} with id {id} not found",
            )

        # Hook: before update
        self.before_update(entity, data)

        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            setattr(entity, field, value)
        entity = self.repo.update(entity)

        # Hook: after update
        self.after_update(entity)

        return self.map_to_response(entity)

    def delete(self, id: int) -> dict:
        """Delete an entity. Raises 404 if not found."""
        entity = self.repo.get_by_id(id)
        if not entity:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"{self.repo.model_class.__name__} with id {id} not found",
            )

        # Hook: before delete
        self.before_delete(entity)

        self.repo.delete(id)
        return {"message": f"{self.repo.model_class.__name__} {id} deleted"}

    def bulk_delete(self, ids: list[int]) -> dict:
        """Delete multiple entities by ID."""
        count = self.repo.bulk_delete(ids)
        return {"message": f"{count} item(s) deleted", "count": count}

    # ─── Hooks (override in subclass) ────────────────────────────────────

    def before_create(self, data: TCreate) -> None:
        """Called before creating an entity. Raise HTTPException to prevent."""
        pass

    def after_create(self, entity: TEntity) -> None:
        """Called after entity is created and committed."""
        pass

    def before_update(self, entity: TEntity, data: TUpdate) -> None:
        """Called before updating. Raise HTTPException to prevent."""
        pass

    def after_update(self, entity: TEntity) -> None:
        """Called after entity is updated and committed."""
        pass

    def before_delete(self, entity: TEntity) -> None:
        """Called before deletion. Raise HTTPException to prevent."""
        pass

    def map_to_response(self, entity: TEntity) -> TResponse:
        """
        Map entity to response schema. Override for custom mapping.
        Default uses Pydantic's from_attributes.
        """
        return self.response_model.model_validate(entity)
